name: stroke_maps_dev
channels:
  - defaults
dependencies:
  - geopandas
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - python>3.10
  - scipy
  - shapely
  - pip:
    - stroke-outcome

